Data model
mumo-esther/Blog-App pull request #2
Opened 2023-06-08 10:55 UTC by mumo-esther

2023-06-08 13:23 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @mumo-esther 
 Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
:heavy_check_mark:  Your Work looks Professional 
:heavy_check_mark: Your Tables are well structured 
:heavy_check_mark:  Nice work so far :+1: 
 
 ## Required Changes 
- [x] Check under the review

 ## Optional suggestions 
N/A

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 13:23 UTC, Alfredbis29 commented on db/migrate/20230301212323_create_posts.rb
> +      t.timestamps
- [OPTIONAL ] I noticed that the column names have been changed to use snake_case instead of CamelCase. For example, the column `Authorid` should br updated to `author_id`, kindly use the snake_case it will make your migration looks more professional :wink:

2023-06-08 13:23 UTC, Alfredbis29 commented on db/migrate/20230301212323_create_posts.rb
> +
- [x] The posts table should have a foreign key column named `author_id`, which references the user's table. This column is used to associate each post with its author. :+1: 
I think this is how it should be 
```
t.references :author, foreign_key: { to_table: 'users' }
```

2023-06-08 13:23 UTC, Alfredbis29 commented on db/migrate/20230301212952_create_likes.rb
> +      t.integer :AuthorId
- [x] Kindly add a foreign key column named `author_id` to the likes table, referencing the `users` table. This column establishes the association between each `like` and its `author`. 
- [x] Create an index on the `author_id` column for efficient querying and joining with the `users` table.
I think this how it should look like :thinking: 
```
    t.references :author, foreign_key: { to_table: 'users' } 
    t.references :post, foreign_key: true 
    t.timestamps 
  end

2023-06-08 13:23 UTC, Alfredbis29 commented on db/migrate/20230301213058_create_comments.rb
> +end
- [ ] Please update the migration for the comments table based on the following requirements: :point_down: 

- [OPTIONAL ]  Change the column names to use snake_case instead of CamelCase. For example, AuthorId should be changed to `author_id`, and `PostId` should be changed to `post_id.`

- [ OPTIONAL] Rename the `Text` column to `text` to align with naming conventions and indicate that it stores the content of the comment.

- [ ]  Implement the references method to create foreign key columns author_id and `post_id`, along with the respective indexes. Use the `foreign_key` option to specify that the `author_id` column references the users table.  set `foreign_key: true` for the `post_id` column to establish a foreign key referencing the primary key of the posts table with the default naming convention (post_id).

You did a great work but I think this how it should look like :thinking: 
```

    t.text :text
    t.timestamps 
    t.references :author, foreign_key: { to_table: 'users' } 
    t.references :post, foreign_key: true 
  end
```

2023-06-08 13:23 UTC, Alfredbis29 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] I noticed that you are missing the `LICENCE` file in your directory and this is the reason we are getting this error :point_down: kindly add the `LICENSE` file in your directory then Import it in your readme :wink: 
![Screenshot from 2023-06-08 15-17-33](https://github.com/mumo-esther/Blog-App/assets/88894525/31829369-b2a3-471e-aa6a-15111e867d04)

2023-06-09 05:01 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @mumo-esther, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean and Organized code

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 05:22 UTC, merged