Validations and model specs
mumo-esther/Blog-App pull request #4
Opened 2023-06-09 18:54 UTC by mumo-esther

In this PR I,
**Add the following validations:**
- For the User model:

  - Name must not be blank.
  - PostsCounter must be an integer greater than or equal to zero.

- For the Post model:

  - Title must not be blank.
  - Title must not exceed 250 characters.
- CommentsCounter must be an integer greater than or equal to zero.

- LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

2023-06-09 19:59 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @mumo-esther,
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 19:59 UTC, tresorsawasawa commented on spec/models/user_spec.rb
> +      expect(User.new(name: 'Chendi', posts_counter: 0)).to be_valid
- [ ] According to the project requirements, Any custom methods in the models should have a corresponding unit test. Kindly make sure the `recent_posts` methods from the User model has a corresponding unit test. ✍🏻

2023-06-09 19:59 UTC, tresorsawasawa commented on spec/models/post_spec.rb
> +    end
- [ ] Same here,  Any custom methods in the models should have a corresponding unit test. Kindly make sure the `update_post_counter` and `recent_comments` methods from the Post model have a corresponding unit test. ✍🏻

2023-06-09 19:59 UTC, tresorsawasawa commented on spec/models/comment_spec.rb
> +      expect(Post.find(1).CommentsCounter).to be 1
- [ ] Same here,  All custom methods in the models should have a corresponding unit test. let's make sure the `comment_counter` method from the Comment model have a corresponding unit test. ✍🏻  

- [ ] Please do the same for the `likes_counters` method from the Like model has a corresponding unit test. :100: :+1:

2023-06-10 07:19 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @mumo-esther     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 10:27 UTC, merged